# Generated by Django 5.0.7 on 2024-09-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsapp', '0005_rename_confirm_passwod_person_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
