# Generated by Django 5.0.7 on 2024-09-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('userpassword', models.CharField(max_length=15)),
            ],
        ),
    ]
