# Generated by Django 5.0.7 on 2024-09-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updateProfile', '0002_userrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecords',
            name='userpassword',
        ),
    ]
