# Generated by Django 5.0.7 on 2024-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsapp', '0003_person_confirm_password_person_email_person_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='person',
            name='confirm_passwod',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
