# Generated by Django 5.1 on 2024-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
