# Generated by Django 5.1 on 2024-09-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Username',
        ),
    ]
