# Generated by Django 5.1 on 2024-09-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='semestre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
