# Generated by Django 5.1 on 2024-09-27 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_usuario_date_joined_usuario_groups_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
