# Generated by Django 5.1 on 2024-09-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_amigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Amigo',
        ),
    ]
