# Generated by Django 5.1 on 2024-09-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_amistad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amistad',
        ),
    ]
