# Generated by Django 5.1 on 2024-09-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_amistad_solicitudamistad'),
    ]

    operations = [
        migrations.AddField(
            model_name='amistad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='SolicitudAmistad',
        ),
    ]
