# Generated by Django 5.1 on 2024-09-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
