# Generated by Django 5.1 on 2024-10-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_foro_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
