# Generated by Django 5.1 on 2024-10-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_foro_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Foro',
        ),
    ]
