# Generated by Django 5.1 on 2024-10-24 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='foro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.foro'),
        ),
    ]
