# Generated by Django 5.1 on 2024-10-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_foro_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='foto_foro',
            field=models.ImageField(blank=True, null=True, upload_to='foros_fotos/'),
        ),
    ]
