# Generated by Django 5.1 on 2024-10-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_foro_foto_foro'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='comentarios_archivos/'),
        ),
        migrations.AlterField(
            model_name='foro',
            name='foto_foro',
            field=models.ImageField(blank=True, null=True, upload_to='foros_media/'),
        ),
    ]
