# Generated by Django 5.1 on 2024-10-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_etiqueta_foro_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
