# Generated by Django 5.0.7 on 2024-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deletefriend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='agregado',
        ),
        migrations.AddField(
            model_name='amigo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amigo',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
